### ISSUE TITLE
新聞レイアウトまとめ

### ISSUE THREAD

**Issue by ya-s-u** [ya-s-u/NewsPaperGenerator#13]
|  | 記事数 | PC | タブレット |
| --- | --- | --- | --- |
| レイアウトA | 5 |  |  |
| レイアウトB | 5 |  |  |
| レイアウトC | 4 |  |  |

**Comment by noritora** [comment]
PCの５記事A
![pc5](https://cloud.githubusercontent.com/assets/12811001/12976640/0c1a88bc-d109-11e5-914b-c9414ecbeb57.jpg)

タブレットの５記事A
![tab5](https://cloud.githubusercontent.com/assets/12811001/12976653/1c4d3bd0-d109-11e5-9475-588fe6a6f24a.jpg)

PCの５記事B
![pc5-b](https://cloud.githubusercontent.com/assets/12811001/12976659/24578af6-d109-11e5-829e-eb41cc21369a.jpg)

タブレットの５記事B
![tab5-b](https://cloud.githubusercontent.com/assets/12811001/12976666/2db23b3c-d109-11e5-895f-6f0aa33061a7.jpg)

PCの４記事
![pc4](https://cloud.githubusercontent.com/assets/12811001/12976671/35e27bdc-d109-11e5-818a-9df86f97fd0e.jpg)

タブレットの４記事
![tab4](https://cloud.githubusercontent.com/assets/12811001/12976677/40fc49ee-d109-11e5-9275-59610a5b1940.jpg)

**Comment by ya-s-u** [comment]
@hyde2able パターン切り替えれるように対応よろしく！

**Comment by pokohide** [comment]
とりあえず３パターン作って変更できるようにした。確認お願いしマッス！
