### ISSUE TITLE
画像保存で切り取りできてない

### ISSUE THREAD

**Issue by ya-s-u** [ya-s-u/NewsPaperGenerator#15]

**Comment by pokohide** [comment]
ローカルから画像を入力した時に、その画像をどうやって使おうか悩んでます。。一旦、ローカルに保存してそれを相対パスで呼び出すか。。

**Comment by ya-s-u** [comment]
それね、、、難しいな、、

**Comment by pokohide** [comment]
やるとしたら、更新時にAjaxで画像データをPostかGetして、サーバー側でfsモジュールを使ってローカルに保存して、"./img/保存した名前.png"みたいな形式で名前を返すルートを作ってやるか。。

自分用メモ。。
