### ISSUE TITLE
段終わりの不自然な空白について

### ISSUE THREAD

**Issue by noritora** [ya-s-u/NewsPaperGenerator#24]
段の終わりに発生する不自然な空白を詰めて表示するように直してほしいです．

![2016-02-27 17 16 31](https://cloud.githubusercontent.com/assets/12811001/13371949/2caf1286-dd76-11e5-923c-93e1ac372078.png)

**Comment by ya-s-u** [comment]
2桁数字が１行に２つ存在するとき１文字溢れる
