### ISSUE TITLE
文字のレイアウトの不具合について

### ISSUE THREAD

**Issue by noritora** [ya-s-u/NewsPaperGenerator#26]
左端の文字がちょん切れてしまったり，文字が重なってしまうバグを直していただきたいです．

![2016-02-27 17 27 56](https://cloud.githubusercontent.com/assets/12811001/13371974/8ca21ae8-dd77-11e5-968c-799aa6bbcd40.png)

**Comment by pokohide** [comment]
記事部分のwidthと記事内容のfontサイズで割って行数を指定してる感じ？
pタグのpaddingとかmarginを考慮したら、行数を綺麗に指定するのはいけそう。。。？

とりあえず見た感じの自分の感想だけ。
時間があったら、やります。

**Comment by ya-s-u** [comment]
これは重いなw
