### ISSUE TITLE
タイトルの数字について

### ISSUE THREAD

**Issue by noritora** [ya-s-u/NewsPaperGenerator#27]
タイトルの数字は本文と異なり，横向きに反転して表示されてしまっているので，縦向きになるように直していただきたいです．

**Comment by pokohide** [comment]
http://tategaki.info/tate_css/howto/
https://www.anothersky.pw/skyward/archives/000167.html
http://qa.atmarkit.co.jp/q/17

これ見てやります。

**Comment by ya-s-u** [comment]
chromeのみ対応すればおk

**Comment by pokohide** [comment]
これも
#32 
と一緒にできたかな。おそらく
