### ISSUE TITLE
HTMLでの出力結果について

### ISSUE THREAD

**Issue by noritora** [ya-s-u/NewsPaperGenerator#28]
出力画面で，背景色がグレーになっているのを白になるように直していただきたいです．

また，縦長のレイアウトで出力した際に，背景色のグレーの部分が横長の領域分しかありませんでした．このことから，縦長の場合に対応できてないと思われましたので，確認していただきたいです．

**Comment by pokohide** [comment]
preview.cssを修正する。
縦長(16:9)の場合も確認します。

**Comment by ya-s-u** [comment]
:dollar:
