### ISSUE TITLE
タイトルについて

### ISSUE THREAD

**Issue by noritora** [ya-s-u/NewsPaperGenerator#31]
タイトルについての要望です．

タイトルの大きさを自由に指定できると記事間の目立ち具合に変化が出せるかもしれません．
最後に，現状デザインの，通常＆黒色の白抜き　に加えて，文字は通常で背景をグレーにできると嬉しいです．

**Comment by pokohide** [comment]
タイトルの大きさ、本文の大きさを変更できるようにできそうです。

> 現状デザインの，通常＆黒色の白抜き　に加えて，文字は通常で背景をグレーにできると嬉しいです．

記事本文の背景がグレーになればいいということですか？そこも、こっちから選択できるように？裏黒の時みたいに

**Comment by ya-s-u** [comment]
:moneybag: :moneybag: :moneybag:

**Comment by pokohide** [comment]
タイトルの大きさ、本文の大きさは変更できるようにしました。

**Comment by pokohide** [comment]
背景のグレーも選択可能に。

**Comment by ya-s-u** [comment]
:ok:
